"""Sinh bảng str.casefold() của CPython cho PythonCaseFold.txt (Core/Services), để C# sắp xếp tệp trong GP5
đúng thứ tự của create-gp5-from-folder.py (sorted(..., key=lambda e: e.name.casefold()))."""
import sys, unicodedata, pathlib
out = []
for cp in range(0x110000):
    if 0xD800 <= cp <= 0xDFFF:
        continue
    c = chr(cp); f = c.casefold()
    if f != c:
        out.append('%X:%s' % (cp, ' '.join('%X' % ord(x) for x in f)))
target = pathlib.Path(__file__).resolve().parents[1] / 'src' / 'PsViethoa.FpkgBuilder.Core' / 'Services' / 'PythonCaseFold.txt'
target.write_text('# str.casefold() of CPython %s (Unicode %s): codepoint:folded codepoints. Generated by scripts/gen-casefold.py\n'
                  % (sys.version.split()[0], unicodedata.unidata_version) + '\n'.join(out) + '\n', encoding='utf-8')
print(len(out), 'entries ->', target)
